Repository NVE/Designsystem, pull requests merged in 2024-08, with the labels that each got.

#209 feat(nve-icon-button): Added new component
  doc-site/components/nve-button.md
  doc-site/components/nve-icon-button.md
  scripts/createNewComponent.js
  src/components/nve-button/nve-button.component.ts
  src/components/nve-button/nve-button.styles.ts
  src/components/nve-icon-button/nve-icon-button.component.ts
  src/components/nve-icon-button/nve-icon-button.styles.ts
  src/interfaces/NveComponent.interface.ts
Labels: Ny komponent

#213 Laget en nve-tag. Kan vise enkel info, og kan ha en lukke-knapp
  doc-site/components/nve-tag.md
  src/components/nve-tag/nve-tag.component.ts
  src/components/nve-tag/nve-tag.styles.ts
  src/nve-designsystem.ts
Labels: ny komponent

#217 Gjort bedre plass til beskrivelse i egenskaps-tabell
  doc-site/.vitepress/theme/components/apidoc/ComponentFields.vue
Labels: documentation

#231 Laget eksempler på setting av verdier i `nve-select`, samt flervalg
  doc-site/components/nve-select.md
Labels: nve-select

#225 Tooltip er nå stylet med nve-farger (variant og saturation)
  doc-site/.vitepress/theme/components/CodeExamplePreview.vue
  doc-site/components/nve-tooltip.md
  src/components/nve-tooltip/nve-tooltip.component.ts
  src/components/nve-tooltip/nve-tooltip.styles.ts
Labels: design - ☑︎ ferdig
